name: dev-guardbear

services:
  guardbear-manager:
    build:
      context: ./guardbear-server
      target: server
    image: dev-guardbear-server
    container_name: guardbear-manager
    hostname: guardbear-manager
    volumes:
      # Server certificates
      - ./certs/root-ca.pem:/etc/guardbear-server/certs/root-ca.pem
      - ./certs/guardbear-manager.pem:/etc/guardbear-server/certs/server.pem
      - ./certs/guardbear-manager.key:/etc/guardbear-server/certs/server-key.pem
      # Indexer certificates
      - ./certs/guardbear-indexer.pem:/etc/guardbear-server/certs/indexer.pem
      - ./certs/guardbear-indexer-key.pem:/etc/guardbear-server/certs/indexer-key.pem
      # Default configuration
      - ./guardbear-server/guardbear-server.yml:/tmp/guardbear-server.yml
      # Source code mappings
      - ../../../framework/scripts/guardbear_server.py:/usr/share/guardbear-server/framework/scripts/guardbear-server.py
      - ../../server_management/scripts/guardbear_server_management_apid.py:/usr/share/guardbear-server/apis/scripts/guardbear-server-management-apid.py
      - ../../communications/scripts/guardbear_comms_apid.py:/usr/share/guardbear-server/apis/scripts/guardbear-comms-apid.py
      - ../../../framework/guardbear:/usr/share/guardbear-server/framework/python/lib/python${GUARDBEAR_PYTHON_VERSION}/site-packages/guardbear
      - ../../server_management/server_management_api:/usr/share/guardbear-server/framework/python/lib/python${GUARDBEAR_PYTHON_VERSION}/site-packages/server_management_api
      - ../../communications/comms_api:/usr/share/guardbear-server/framework/python/lib/python${GUARDBEAR_PYTHON_VERSION}/site-packages/comms_api
      # Vulnerability Detector feed
      - vd_feed:/var/lib/guardbear-server/queue
    ports:
      # Management API
      - 55000:55000
      # Communications API
      - 27000:27000
    entrypoint:
      - /scripts/entrypoint.sh
      - guardbear-manager
      - manager-node
      - manager
    depends_on:
      - guardbear-indexer

  guardbear-worker1:
    image: dev-guardbear-server
    hostname: guardbear-worker1
    container_name: guardbear-worker1
    volumes:
      # Server certificates
      - ./certs/root-ca.pem:/etc/guardbear-server/certs/root-ca.pem
      - ./certs/guardbear-worker1.pem:/etc/guardbear-server/certs/server.pem
      - ./certs/guardbear-worker1.key:/etc/guardbear-server/certs/server-key.pem
      # Indexer certificates
      - ./certs/guardbear-indexer.pem:/etc/guardbear-server/certs/indexer.pem
      - ./certs/guardbear-indexer-key.pem:/etc/guardbear-server/certs/indexer-key.pem
      # Default configuration
      - ./guardbear-server/guardbear-server.yml:/tmp/guardbear-server.yml
      # Source code mappings
      - ../../../framework/scripts/guardbear_server.py:/usr/share/guardbear-server/framework/scripts/guardbear-server.py
      - ../../server_management/scripts/guardbear_server_management_apid.py:/usr/share/guardbear-server/apis/scripts/guardbear-server-management-apid.py
      - ../../communications/scripts/guardbear_comms_apid.py:/usr/share/guardbear-server/apis/scripts/guardbear-comms-apid.py
      - ../../../framework/guardbear:/usr/share/guardbear-server/framework/python/lib/python${GUARDBEAR_PYTHON_VERSION}/site-packages/guardbear
      - ../../server_management/server_management_api:/usr/share/guardbear-server/framework/python/lib/python${GUARDBEAR_PYTHON_VERSION}/site-packages/server_management_api
      - ../../communications/comms_api:/usr/share/guardbear-server/framework/python/lib/python${GUARDBEAR_PYTHON_VERSION}/site-packages/comms_api
      # Vulnerability Detector feed
      - vd_feed:/var/lib/guardbear-server/queue
    depends_on:
      - guardbear-manager
      - guardbear-indexer
    ports:
      # Management API
      - 55001:55000
      # Communications API
      - 27001:27000
    entrypoint:
      - /scripts/entrypoint.sh
      - guardbear-manager
      - worker1
      - worker

  guardbear-worker2:
    image: dev-guardbear-server
    hostname: guardbear-worker2
    container_name: guardbear-worker2
    volumes:
      # Server certificates
      - ./certs/root-ca.pem:/etc/guardbear-server/certs/root-ca.pem
      - ./certs/guardbear-worker2.pem:/etc/guardbear-server/certs/server.pem
      - ./certs/guardbear-worker2.key:/etc/guardbear-server/certs/server-key.pem
      # Indexer certificates
      - ./certs/guardbear-indexer.pem:/etc/guardbear-server/certs/indexer.pem
      - ./certs/guardbear-indexer-key.pem:/etc/guardbear-server/certs/indexer-key.pem
      # Default configuration
      - ./guardbear-server/guardbear-server.yml:/tmp/guardbear-server.yml
      # Source code mappings
      - ../../../framework/scripts/guardbear_server.py:/usr/share/guardbear-server/framework/scripts/guardbear-server.py
      - ../../server_management/scripts/guardbear_server_management_apid.py:/usr/share/guardbear-server/apis/scripts/guardbear-server-management-apid.py
      - ../../communications/scripts/guardbear_comms_apid.py:/usr/share/guardbear-server/apis/scripts/guardbear-comms-apid.py
      - ../../../framework/guardbear:/usr/share/guardbear-server/framework/python/lib/python${GUARDBEAR_PYTHON_VERSION}/site-packages/guardbear
      - ../../server_management/server_management_api:/usr/share/guardbear-server/framework/python/lib/python${GUARDBEAR_PYTHON_VERSION}/site-packages/server_management_api
      - ../../communications/comms_api:/usr/share/guardbear-server/framework/python/lib/python${GUARDBEAR_PYTHON_VERSION}/site-packages/comms_api
      # Vulnerability Detector feed
      - vd_feed:/var/lib/guardbear-server/queue
    depends_on:
      - guardbear-manager
      - guardbear-indexer
    ports:
      # Management API
      - 55002:55000
      # Communications API
      - 27002:27000
    entrypoint:
      - /scripts/entrypoint.sh
      - guardbear-manager
      - worker2
      - worker

  guardbear-indexer:
    build:
      context: ./guardbear-indexer
    image: dev-guardbear-indexer
    hostname: guardbear-indexer
    container_name: guardbear-indexer
    volumes:
      - ./certs/root-ca.pem:/usr/share/opensearch/config/root-ca.pem
      - ./certs/guardbear-indexer.pem:/usr/share/opensearch/config/indexer.pem
      - ./certs/guardbear-indexer.key:/usr/share/opensearch/config/indexer.key
      - ./certs/guardbear-indexer-key.pem:/usr/share/opensearch/config/indexer-key.pem
    ports:
      - 9200:9200
    environment:
      - node.name=guardbear-indexer
      - discovery.type=single-node
      - plugins.security.ssl.transport.pemcert_filepath=indexer.pem
      - plugins.security.ssl.transport.pemkey_filepath=indexer-key.pem
      - plugins.security.ssl.transport.pemtrustedcas_filepath=root-ca.pem
      - plugins.security.ssl.http.enabled=true
      - plugins.security.ssl.http.pemcert_filepath=indexer.pem
      - plugins.security.ssl.http.pemkey_filepath=indexer-key.pem
      - plugins.security.ssl.http.pemtrustedcas_filepath=root-ca.pem
      # Allow using server certificates to authenticate
      - plugins.security.ssl.http.clientauth_mode=NONE
      - plugins.security.allow_default_init_securityindex=true
      - cluster.blocks.create_index=false
      # Prevent execution of bundled demo script which installs demo certificates and security configurations to OpenSearch
      - DISABLE_INSTALL_DEMO_CONFIG=true

  nginx-lb:
    build:
      context: ./nginx-lb
    image: dev-nginx-lb
    container_name: nginx-lb
    restart: on-failure:5
    entrypoint:
      - /scripts/entrypoint.sh
    depends_on:
      - guardbear-manager
      - guardbear-worker1
      - guardbear-worker2

  guardbear-agent:
    build:
      context: ./guardbear-agent
      target: agent
    image: dev-guardbear-agent
    container_name: guardbear-agent
    volumes:
      - ./guardbear-agent/guardbear-agent.yml:/etc/guardbear-agent/guardbear-agent.yml
    environment:
      USER: guardbear
      PASSWORD: guardbear
    depends_on:
      - guardbear-manager
      - guardbear-worker1
      - guardbear-worker2
      - nginx-lb

volumes:
  vd_feed:
