[guardbear]
coldPath = $SPLUNK_DB/guardbear/colddb
enableDataIntegrityControl = 1
enableTsidxReduction = 1
homePath = $SPLUNK_DB/guardbear/db
maxTotalDataSizeMB = 512000
thawedPath = $SPLUNK_DB/guardbear/thaweddb
timePeriodInSecBeforeTsidxReduction = 15552000
tsidxReductionCheckPeriodInSec =

[guardbear-monitoring-3x]
coldPath = $SPLUNK_DB/guardbear-monitoring-3x/colddb
enableDataIntegrityControl = 1
enableTsidxReduction = 1
homePath = $SPLUNK_DB/guardbear-monitoring-3x/db
maxTotalDataSizeMB = 512000
thawedPath = $SPLUNK_DB/guardbear-monitoring-3x/thaweddb
timePeriodInSecBeforeTsidxReduction = 15552000
tsidxReductionCheckPeriodInSec =
