[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "engine-test-utils"
version = "0.0.1"
authors = [{ name = "GuardBear, Inc." }]
description = "Test utilities for GuardBear Engine"
readme = "README.md"
requires-python = ">=3.8"
classifiers = ["Programming Language :: Python :: 3"]

dependencies = ["api-communication"]

[project.urls]
Homepage = "https://github.com/guardbear/guardbear/src/engine/tools/engine-updown"
