#!/bin/sh

# Copyright (C) 2015, GuardBear Inc.
# OSSEC         Controls GuardBear on Redhat-based systems
# Author:       Kayvan A. Sylvan <kayvan@sylvan.com>
# Author:       Daniel B. Cid <dcid@ossec.net>
#
# chkconfig: 2345 99 15
# description: Starts and stops GuardBear (Host Intrusion Detection System)
#
# This will work on Redhat systems (maybe others too)

# Source function library.
export LANG=C

. /etc/init.d/functions

GUARDBEAR_HOME=GUARDBEAR_HOME_TMP
GUARDBEAR_SERVER="${GUARDBEAR_HOME}/usr/share/guardbear-server/bin/guardbear-server"

start() {
    echo -n "Starting GuardBear: "
    ${GUARDBEAR_SERVER} start > /dev/null
    RETVAL=$?
    if [ $RETVAL -eq 0 ]; then
        success
    else
        failure
    fi
    echo
    return $RETVAL
}

stop() {
    echo -n "Stopping GuardBear: "
    ${GUARDBEAR_SERVER} stop > /dev/null
    RETVAL=$?
    if [ $RETVAL -eq 0 ]; then
        success
    else
        failure
    fi
    echo
    return $RETVAL
}

status() {
    ${GUARDBEAR_SERVER} status
    RETVAL=$?
    return $RETVAL
}

case "$1" in
start)
    start
    ;;
stop)
    stop
    ;;
restart)
    stop
    start
    ;;
status)
    status
    ;;
*)
    echo "*** Usage: ossec {start|stop|restart|status}"
    exit 1
esac

exit $?
